services:
  - type: web_service
    name: ShopEZ Server
    env: node
    region: oregon
    branch: main
    repo: https://github.com/saiteja-crypto/SHOPEZ.git
    root: server
    buildCommand: npm install
    startCommand: npm start
    plan: starter
    autoDeploy: true
